workflows:
  android-build:
    name: Android APK Build

    environment:
      node: latest

    working_directory: frontend

    scripts:
      - pwd
      - ls -la
      - npm install
      - npx expo prebuild --platform android
      - cd android
      - ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk
