workflows:
  android-build:
    name: Android Build
    environment:
      node: latest
    scripts:
      - npm install
      - npx expo prebuild --platform android
      - cd android
      - ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
